---
title: "Penguins EDA"
format:
  html:
    code-fold: true
---

## Penguin Size and Mass by Sex and Species

```{r setup, echo=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
library(palmerpenguins)
library(dplyr)
library(dbplyr)
library(ggplot2)
library(DBI)
library(duckdb)

con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "my-db.duckdb")
df <- palmerpenguins::penguins
```

```{r, echo=FALSE}
#df %>%
#  group_by(species, sex) %>%
#  summarise(
#    across(
#      where(is.numeric), 
#      \(x) mean(x, na.rm = TRUE)
#      )
#    ) %>%
#  knitr::kable()
```

```{r}
df %>%
  group_by(species, sex) %>%
  summarise(
    across(
        ends_with("mm") | ends_with("g"),
      \(x) mean(x, na.rm = TRUE)
      )
    ) %>%
  dplyr::collect() %>%
  knitr::kable()
```

## Penguin Size vs Mass by Species

```{r}
df %>%
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r}
DBI::dbDisconnect(con, shutdown = TRUE)
```
